-- GENERATED by worker/seedSql.ts from fixtures/. Do not edit by hand (run `npx vitest run tests/seed-sql.test.ts -u`).
-- Same data every client bootstraps locally; stamped with SEED_HLC so any real edit wins; never in change_log.

INSERT INTO price_registry (ingredient_id, display_name, price_per_unit, pricing_unit, last_updated, hlc) VALUES
('ampalaya', 'Ampalaya', 90, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('bagoong', 'Shrimp paste (bagoong)', 45, 'bottle', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('bay_leaf', 'Bay leaf', 15, 'pack', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('beef_chuck', 'Beef chuck', 450, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('beef_shank', 'Beef shank', 400, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('beef_sirloin', 'Beef sirloin', 520, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('bell_pepper', 'Bell pepper', 180, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('cabbage', 'Cabbage', 60, 'head', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('carrot', 'Carrot', 80, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('chicken_cutup', 'Chicken cut-up', 190, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('chicken_thigh', 'Chicken thigh', 220, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('coconut_milk', 'Coconut milk', 38, 'can', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('cooking_oil', 'Cooking oil', 90, 'bottle', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('eggplant', 'Eggplant', 80, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('fish_sauce', 'Fish sauce', 30, 'bottle', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('garlic', 'Garlic', 160, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('ginger', 'Ginger', 140, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('ground_pork', 'Ground pork', 300, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('kalabasa', 'Kalabasa', 45, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('kangkong', 'Kangkong', 20, 'pack', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('liver_spread', 'Liver spread', 18, 'can', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('malunggay', 'Malunggay leaves', 15, 'pack', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('mung_beans', 'Mung beans', 55, 'pack', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('okra', 'Okra', 90, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('peanut_butter', 'Peanut butter', 70, 'bottle', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('pork_belly', 'Pork belly', 380, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('pork_hock', 'Pork hock', 280, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('pork_shoulder', 'Pork shoulder', 320, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('potato', 'Potato', 90, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('radish', 'Radish', 60, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('re250_container', 'RE-250 container', 4, 'piece', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('red_onion', 'Red onion', 120, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('sayote', 'Sayote', 60, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('sinigang_mix', 'Sinigang mix', 18, 'pack', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('sitaw', 'Sitaw', 100, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('soy_sauce', 'Soy sauce', 28, 'bottle', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('tomato', 'Tomato', 100, 'kg', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('tomato_sauce', 'Tomato sauce', 22, 'pouch', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed'),
('vinegar', 'Vinegar', 25, 'bottle', '2026-10-04T00:00:00.000Z', '000000000000000-00000-seed');

INSERT INTO price_observations (id, ingredient_id, kind, price, observed_at, cycle_id, device_id) VALUES
('seed:ampalaya', 'ampalaya', 'seed', 90, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:bagoong', 'bagoong', 'seed', 45, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:bay_leaf', 'bay_leaf', 'seed', 15, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:beef_chuck', 'beef_chuck', 'seed', 450, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:beef_shank', 'beef_shank', 'seed', 400, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:beef_sirloin', 'beef_sirloin', 'seed', 520, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:bell_pepper', 'bell_pepper', 'seed', 180, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:cabbage', 'cabbage', 'seed', 60, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:carrot', 'carrot', 'seed', 80, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:chicken_cutup', 'chicken_cutup', 'seed', 190, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:chicken_thigh', 'chicken_thigh', 'seed', 220, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:coconut_milk', 'coconut_milk', 'seed', 38, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:cooking_oil', 'cooking_oil', 'seed', 90, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:eggplant', 'eggplant', 'seed', 80, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:fish_sauce', 'fish_sauce', 'seed', 30, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:garlic', 'garlic', 'seed', 160, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:ginger', 'ginger', 'seed', 140, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:ground_pork', 'ground_pork', 'seed', 300, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:kalabasa', 'kalabasa', 'seed', 45, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:kangkong', 'kangkong', 'seed', 20, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:liver_spread', 'liver_spread', 'seed', 18, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:malunggay', 'malunggay', 'seed', 15, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:mung_beans', 'mung_beans', 'seed', 55, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:okra', 'okra', 'seed', 90, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:peanut_butter', 'peanut_butter', 'seed', 70, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:pork_belly', 'pork_belly', 'seed', 380, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:pork_hock', 'pork_hock', 'seed', 280, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:pork_shoulder', 'pork_shoulder', 'seed', 320, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:potato', 'potato', 'seed', 90, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:radish', 'radish', 'seed', 60, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:re250_container', 're250_container', 'seed', 4, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:red_onion', 'red_onion', 'seed', 120, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:sayote', 'sayote', 'seed', 60, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:sinigang_mix', 'sinigang_mix', 'seed', 18, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:sitaw', 'sitaw', 'seed', 100, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:soy_sauce', 'soy_sauce', 'seed', 28, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:tomato', 'tomato', 'seed', 100, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:tomato_sauce', 'tomato_sauce', 'seed', 22, '2026-10-04T00:00:00.000Z', NULL, 'seed'),
('seed:vinegar', 'vinegar', 'seed', 25, '2026-10-04T00:00:00.000Z', NULL, 'seed');

INSERT INTO ingredient_meta (ingredient_id, aisle, storage_class, surface_prep, avg_unit_mass_g, updated_at) VALUES
('ampalaya', 'produce', 'loose_produce', 'Wash and seed', 250, '000000000000000-00000-seed'),
('bagoong', 'canned_dry', 'perishable_once_opened', NULL, NULL, '000000000000000-00000-seed'),
('bay_leaf', 'canned_dry', 'shelf_stable_sealed', NULL, NULL, '000000000000000-00000-seed'),
('beef_chuck', 'fresh_meat', 'fresh_meat', NULL, NULL, '000000000000000-00000-seed'),
('beef_shank', 'fresh_meat', 'fresh_meat', NULL, NULL, '000000000000000-00000-seed'),
('beef_sirloin', 'fresh_meat', 'fresh_meat', NULL, NULL, '000000000000000-00000-seed'),
('bell_pepper', 'produce', 'loose_produce', 'Wash and seed', 150, '000000000000000-00000-seed'),
('cabbage', 'produce', 'loose_produce', 'Wash', 900, '000000000000000-00000-seed'),
('carrot', 'produce', 'loose_produce', 'Wash and peel', 100, '000000000000000-00000-seed'),
('chicken_cutup', 'fresh_meat', 'fresh_meat', NULL, NULL, '000000000000000-00000-seed'),
('chicken_thigh', 'fresh_meat', 'fresh_meat', NULL, NULL, '000000000000000-00000-seed'),
('coconut_milk', 'canned_dry', 'shelf_stable_sealed', NULL, NULL, '000000000000000-00000-seed'),
('cooking_oil', 'canned_dry', 'shelf_stable_sealed', NULL, NULL, '000000000000000-00000-seed'),
('eggplant', 'produce', 'loose_produce', 'Wash', 200, '000000000000000-00000-seed'),
('fish_sauce', 'canned_dry', 'shelf_stable_sealed', NULL, NULL, '000000000000000-00000-seed'),
('garlic', 'produce', 'loose_produce', 'Peel', NULL, '000000000000000-00000-seed'),
('ginger', 'produce', 'loose_produce', 'Wash and peel', NULL, '000000000000000-00000-seed'),
('ground_pork', 'fresh_meat', 'fresh_meat', NULL, NULL, '000000000000000-00000-seed'),
('kalabasa', 'produce', 'loose_produce', 'Wash, seed and peel', NULL, '000000000000000-00000-seed'),
('kangkong', 'produce', 'loose_produce', 'Wash', NULL, '000000000000000-00000-seed'),
('liver_spread', 'canned_dry', 'shelf_stable_sealed', NULL, NULL, '000000000000000-00000-seed'),
('malunggay', 'produce', 'loose_produce', 'Wash and strip', NULL, '000000000000000-00000-seed'),
('mung_beans', 'canned_dry', 'shelf_stable_sealed', NULL, NULL, '000000000000000-00000-seed'),
('okra', 'produce', 'loose_produce', 'Wash and trim', NULL, '000000000000000-00000-seed'),
('peanut_butter', 'canned_dry', 'shelf_stable_sealed', NULL, NULL, '000000000000000-00000-seed'),
('pork_belly', 'fresh_meat', 'fresh_meat', NULL, NULL, '000000000000000-00000-seed'),
('pork_hock', 'fresh_meat', 'fresh_meat', NULL, NULL, '000000000000000-00000-seed'),
('pork_shoulder', 'fresh_meat', 'fresh_meat', NULL, NULL, '000000000000000-00000-seed'),
('potato', 'produce', 'loose_produce', 'Wash and peel', 150, '000000000000000-00000-seed'),
('radish', 'produce', 'loose_produce', 'Wash and peel', 200, '000000000000000-00000-seed'),
('re250_container', 'disposable', 'disposable', NULL, NULL, '000000000000000-00000-seed'),
('red_onion', 'produce', 'loose_produce', 'Peel', 110, '000000000000000-00000-seed'),
('sayote', 'produce', 'loose_produce', 'Wash and peel', 250, '000000000000000-00000-seed'),
('sinigang_mix', 'canned_dry', 'shelf_stable_sealed', NULL, NULL, '000000000000000-00000-seed'),
('sitaw', 'produce', 'loose_produce', 'Wash and trim', NULL, '000000000000000-00000-seed'),
('soy_sauce', 'canned_dry', 'shelf_stable_sealed', NULL, NULL, '000000000000000-00000-seed'),
('tomato', 'produce', 'loose_produce', 'Wash', 90, '000000000000000-00000-seed'),
('tomato_sauce', 'canned_dry', 'perishable_once_opened', NULL, NULL, '000000000000000-00000-seed'),
('vinegar', 'canned_dry', 'shelf_stable_sealed', NULL, NULL, '000000000000000-00000-seed');

-- beef-bistek
INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ('beef-bistek', 'Beef Bistek Tagalog', 10, 'beef', 'soy_vinegar', 'TIER_2_HARDY', 'PRIORITY_2_FAST_SAUTE', 860, 'Fill solids first, sauce after.', '000000000000000-00000-seed', 0);
INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES
('beef-bistek', 0, 'beef_sirloin', 'Beef sirloin', 'SLICED_THIN', 'Ask for thin steak slices against the grain', 'granular', NULL, 130, 'g', NULL, NULL, NULL),
('beef-bistek', 1, 'red_onion', 'Red onion', 'SLICED_RINGS', NULL, 'granular', NULL, 30, 'g', NULL, NULL, NULL),
('beef-bistek', 2, 'garlic', 'Garlic', 'MINCED', NULL, 'granular', NULL, 2, 'g', NULL, NULL, NULL),
('beef-bistek', 3, 'soy_sauce', 'Soy sauce', 'NONE', NULL, 'continuous', NULL, 25, 'ml', '385 mL bottle', 385, 1),
('beef-bistek', 4, 'vinegar', 'Vinegar', 'NONE', NULL, 'continuous', NULL, 8, 'ml', '385 mL bottle', 385, 1),
('beef-bistek', 5, 'cooking_oil', 'Cooking oil', 'NONE', NULL, 'continuous', NULL, 3, 'ml', '1 L bottle', 1000, 1);
INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES
('beef-bistek', 0, 'Marinate beef in soy sauce and calamansi until the surface looks glossy.'),
('beef-bistek', 1, 'Sear beef in smoking oil until browned; transfer to plate.'),
('beef-bistek', 2, 'Sauté onion rings until just wilted, then return beef.'),
('beef-bistek', 3, 'Simmer in the marinade until the sauce turns syrupy and the beef feels tender.');

-- chicken-adobo
INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ('chicken-adobo', 'Chicken Adobo', 10, 'chicken', 'soy_vinegar', 'TIER_2_HARDY', 'PRIORITY_1_SLOW_BRAISE', 410, 'Fill solids first, sauce after.', '000000000000000-00000-seed', 0);
INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES
('chicken-adobo', 0, 'chicken_thigh', 'Chicken thigh', 'WHOLE', 'Ask for bone-in thighs, skin on', 'discrete', 1, 150, 'g', NULL, NULL, NULL),
('chicken-adobo', 1, 'garlic', 'Garlic', 'MINCED', NULL, 'granular', NULL, 6, 'g', NULL, NULL, NULL),
('chicken-adobo', 2, 'soy_sauce', 'Soy sauce', 'NONE', NULL, 'continuous', NULL, 30, 'ml', '385 mL bottle', 385, 1),
('chicken-adobo', 3, 'vinegar', 'Vinegar', 'NONE', NULL, 'continuous', NULL, 25, 'ml', '385 mL bottle', 385, 1),
('chicken-adobo', 4, 'bay_leaf', 'Bay leaf', 'WHOLE', NULL, 'discrete', 1, 0.2, 'pc', 'pack of 20 leaves', 20, 1);
INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES
('chicken-adobo', 0, 'Combine chicken, soy sauce, vinegar, garlic and bay leaf; rest until well coated.'),
('chicken-adobo', 1, 'Bring to a simmer, then cover and cook until the juices run clear.'),
('chicken-adobo', 2, 'Uncover and reduce until the sauce turns glossy.'),
('chicken-adobo', 3, 'Sear skin side in a dry pan until browned and crisp.');

-- chicken-afritada
INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ('chicken-afritada', 'Chicken Afritada', 10, 'chicken', 'tomato', 'TIER_2_HARDY', 'PRIORITY_1_SLOW_BRAISE', 510, 'Fill solids first, sauce after.', '000000000000000-00000-seed', 0);
INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES
('chicken-afritada', 0, 'chicken_cutup', 'Chicken cut-up', 'WHOLE', 'Ask for a cut-up chicken, bone-in', 'discrete', 1, 150, 'g', NULL, NULL, NULL),
('chicken-afritada', 1, 'potato', 'Potato', 'LARGE_DICE', NULL, 'discrete', 2, 40, 'g', NULL, NULL, NULL),
('chicken-afritada', 2, 'carrot', 'Carrot', 'ROLL_CUT', NULL, 'granular', NULL, 25, 'g', NULL, NULL, NULL),
('chicken-afritada', 3, 'bell_pepper', 'Bell pepper', 'LARGE_DICE', NULL, 'granular', NULL, 20, 'g', NULL, NULL, NULL),
('chicken-afritada', 4, 'red_onion', 'Red onion', 'MEDIUM_DICE', NULL, 'granular', NULL, 15, 'g', NULL, NULL, NULL),
('chicken-afritada', 5, 'garlic', 'Garlic', 'MINCED', NULL, 'granular', NULL, 3, 'g', NULL, NULL, NULL),
('chicken-afritada', 6, 'tomato_sauce', 'Tomato sauce', 'NONE', NULL, 'continuous', NULL, 25, 'g', '250 g pouch', 250, 1),
('chicken-afritada', 7, 'cooking_oil', 'Cooking oil', 'NONE', NULL, 'continuous', NULL, 3, 'ml', '1 L bottle', 1000, 1);
INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES
('chicken-afritada', 0, 'Brown chicken in smoking oil on all sides; set aside.'),
('chicken-afritada', 1, 'Sauté onion until glassy, then garlic until golden.'),
('chicken-afritada', 2, 'Return chicken with tomato sauce and water; cover and simmer until tender.'),
('chicken-afritada', 3, 'Add potatoes and carrots; simmer until easily pierced.'),
('chicken-afritada', 4, 'Fold in peppers and cook until just softened.');

-- chicken-tinola
INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ('chicken-tinola', 'Chicken Tinola', 10, 'chicken', 'clear_broth', 'TIER_1_FRESH', 'PRIORITY_2_FAST_SAUTE', 485, 'Fill solids first, sauce after.', '000000000000000-00000-seed', 0);
INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES
('chicken-tinola', 0, 'chicken_cutup', 'Chicken cut-up', 'WHOLE', 'Ask for a cut-up chicken, bone-in', 'discrete', 1, 150, 'g', NULL, NULL, NULL),
('chicken-tinola', 1, 'sayote', 'Sayote', 'WEDGES', NULL, 'discrete', 2, 70, 'g', NULL, NULL, NULL),
('chicken-tinola', 2, 'ginger', 'Ginger', 'SLICED_THIN', NULL, 'granular', NULL, 5, 'g', NULL, NULL, NULL),
('chicken-tinola', 3, 'red_onion', 'Red onion', 'SLICED_RINGS', NULL, 'granular', NULL, 10, 'g', NULL, NULL, NULL),
('chicken-tinola', 4, 'malunggay', 'Malunggay leaves', 'NONE', NULL, 'granular', NULL, 0.1, 'pack', NULL, NULL, NULL),
('chicken-tinola', 5, 'garlic', 'Garlic', 'MINCED', NULL, 'granular', NULL, 2, 'g', NULL, NULL, NULL),
('chicken-tinola', 6, 'fish_sauce', 'Fish sauce', 'NONE', NULL, 'continuous', NULL, 8, 'ml', '350 mL bottle', 350, 1),
('chicken-tinola', 7, 'cooking_oil', 'Cooking oil', 'NONE', NULL, 'continuous', NULL, 3, 'ml', '1 L bottle', 1000, 1);
INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES
('chicken-tinola', 0, 'Sauté ginger, garlic and onion in hot oil until fragrant.'),
('chicken-tinola', 1, 'Add chicken; stir until the surface turns opaque.'),
('chicken-tinola', 2, 'Pour in water, cover and simmer until the chicken is tender.'),
('chicken-tinola', 3, 'Add sayote; simmer until easily pierced.'),
('chicken-tinola', 4, 'Season with fish sauce and fold in malunggay until just wilted.');

-- ginataang-kalabasa-sitaw
INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ('ginataang-kalabasa-sitaw', 'Ginataang Kalabasa at Sitaw', 10, 'vegetable', 'coconut', 'TIER_1_FRESH', 'PRIORITY_3_FINISH_LAST', 155, 'Fill solids first, sauce after.', '000000000000000-00000-seed', 0);
INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES
('ginataang-kalabasa-sitaw', 0, 'kalabasa', 'Kalabasa', 'LARGE_DICE', NULL, 'granular', NULL, 60, 'g', NULL, NULL, NULL),
('ginataang-kalabasa-sitaw', 1, 'sitaw', 'Sitaw', 'ROUGH_CHOP', 'Cut into finger lengths', 'granular', NULL, 40, 'g', NULL, NULL, NULL),
('ginataang-kalabasa-sitaw', 2, 'coconut_milk', 'Coconut milk', 'NONE', NULL, 'continuous', NULL, 40, 'ml', '400 mL can', 400, 1),
('ginataang-kalabasa-sitaw', 3, 'red_onion', 'Red onion', 'SMALL_DICE', NULL, 'granular', NULL, 10, 'g', NULL, NULL, NULL),
('ginataang-kalabasa-sitaw', 4, 'garlic', 'Garlic', 'MINCED', NULL, 'granular', NULL, 2, 'g', NULL, NULL, NULL),
('ginataang-kalabasa-sitaw', 5, 'ginger', 'Ginger', 'MINCED', NULL, 'granular', NULL, 3, 'g', NULL, NULL, NULL),
('ginataang-kalabasa-sitaw', 6, 'fish_sauce', 'Fish sauce', 'NONE', NULL, 'continuous', NULL, 8, 'ml', '350 mL bottle', 350, 1);
INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES
('ginataang-kalabasa-sitaw', 0, 'Simmer coconut milk with onion, garlic and ginger until fragrant.'),
('ginataang-kalabasa-sitaw', 1, 'Add kalabasa; simmer until easily pierced.'),
('ginataang-kalabasa-sitaw', 2, 'Add sitaw; cook until bright green and just tender.'),
('ginataang-kalabasa-sitaw', 3, 'Season with fish sauce and finish until the sauce coats the vegetables.');

-- ginisang-munggo
INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ('ginisang-munggo', 'Ginisang Munggo', 10, 'vegetable', 'clear_broth', 'TIER_2_HARDY', 'PRIORITY_1_SLOW_BRAISE', 220, 'Fill solids first, sauce after.', '000000000000000-00000-seed', 0);
INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES
('ginisang-munggo', 0, 'mung_beans', 'Mung beans', 'NONE', NULL, 'continuous', NULL, 30, 'g', '500 g pack', 500, 1),
('ginisang-munggo', 1, 'red_onion', 'Red onion', 'SMALL_DICE', NULL, 'granular', NULL, 15, 'g', NULL, NULL, NULL),
('ginisang-munggo', 2, 'garlic', 'Garlic', 'MINCED', NULL, 'granular', NULL, 3, 'g', NULL, NULL, NULL),
('ginisang-munggo', 3, 'tomato', 'Tomato', 'MEDIUM_DICE', NULL, 'granular', NULL, 20, 'g', NULL, NULL, NULL),
('ginisang-munggo', 4, 'fish_sauce', 'Fish sauce', 'NONE', NULL, 'continuous', NULL, 8, 'ml', '350 mL bottle', 350, 1),
('ginisang-munggo', 5, 'cooking_oil', 'Cooking oil', 'NONE', NULL, 'continuous', NULL, 3, 'ml', '1 L bottle', 1000, 1);
INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES
('ginisang-munggo', 0, 'Boil mung beans until soft and splitting.'),
('ginisang-munggo', 1, 'Sauté onion, garlic and tomato until jammy.'),
('ginisang-munggo', 2, 'Stir the sauté into the beans; simmer until thick and creamy.'),
('ginisang-munggo', 3, 'Season with fish sauce until savory.');

-- ginisang-sayote-ground-pork
INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ('ginisang-sayote-ground-pork', 'Ginisang Sayote with Ground Pork', 10, 'pork', 'clear_broth', 'TIER_1_FRESH', 'PRIORITY_2_FAST_SAUTE', 390, 'Fill solids first, sauce after.', '000000000000000-00000-seed', 0);
INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES
('ginisang-sayote-ground-pork', 0, 'ground_pork', 'Ground pork', 'NONE', NULL, 'continuous', NULL, 60, 'g', NULL, NULL, NULL),
('ginisang-sayote-ground-pork', 1, 'sayote', 'Sayote', 'JULIENNE', NULL, 'granular', NULL, 80, 'g', NULL, NULL, NULL),
('ginisang-sayote-ground-pork', 2, 'red_onion', 'Red onion', 'SMALL_DICE', NULL, 'granular', NULL, 15, 'g', NULL, NULL, NULL),
('ginisang-sayote-ground-pork', 3, 'garlic', 'Garlic', 'MINCED', NULL, 'granular', NULL, 3, 'g', NULL, NULL, NULL),
('ginisang-sayote-ground-pork', 4, 'tomato', 'Tomato', 'MEDIUM_DICE', NULL, 'granular', NULL, 20, 'g', NULL, NULL, NULL),
('ginisang-sayote-ground-pork', 5, 'fish_sauce', 'Fish sauce', 'NONE', NULL, 'continuous', NULL, 8, 'ml', '350 mL bottle', 350, 1),
('ginisang-sayote-ground-pork', 6, 'cooking_oil', 'Cooking oil', 'NONE', NULL, 'continuous', NULL, 3, 'ml', '1 L bottle', 1000, 1);
INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES
('ginisang-sayote-ground-pork', 0, 'Sauté garlic, onion and tomato until soft and fragrant.'),
('ginisang-sayote-ground-pork', 1, 'Crumble in ground pork; stir until no pink remains.'),
('ginisang-sayote-ground-pork', 2, 'Add sayote and a splash of water; cover and steam until tender-crisp.'),
('ginisang-sayote-ground-pork', 3, 'Season with fish sauce and finish uncovered until the liquid thickens.');

-- kare-kare
INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ('kare-kare', 'Kare-Kare', 10, 'beef', 'peanut', 'TIER_2_HARDY', 'PRIORITY_1_SLOW_BRAISE', 685, 'Fill solids first, sauce after.', '000000000000000-00000-seed', 0);
INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES
('kare-kare', 0, 'beef_shank', 'Beef shank', 'LARGE_DICE', 'Ask for shank cut into thick rounds', 'discrete', 3, 110, 'g', NULL, NULL, NULL),
('kare-kare', 1, 'kalabasa', 'Kalabasa', 'LARGE_DICE', NULL, 'granular', NULL, 40, 'g', NULL, NULL, NULL),
('kare-kare', 2, 'red_onion', 'Red onion', 'MEDIUM_DICE', NULL, 'granular', NULL, 15, 'g', NULL, NULL, NULL),
('kare-kare', 3, 'garlic', 'Garlic', 'MINCED', NULL, 'granular', NULL, 3, 'g', NULL, NULL, NULL),
('kare-kare', 4, 'peanut_butter', 'Peanut butter', 'NONE', NULL, 'continuous', NULL, 20, 'g', '270 g jar', 270, 1),
('kare-kare', 5, 'bagoong', 'Shrimp paste (bagoong)', 'NONE', NULL, 'continuous', NULL, 8, 'g', '250 g jar', 250, 1),
('kare-kare', 6, 'cooking_oil', 'Cooking oil', 'NONE', NULL, 'continuous', NULL, 3, 'ml', '1 L bottle', 1000, 1);
INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES
('kare-kare', 0, 'Simmer beef covered until fork-tender and the broth turns rich.'),
('kare-kare', 1, 'Sauté onion and garlic until glassy and golden.'),
('kare-kare', 2, 'Stir peanut butter into hot broth until smooth and thick.'),
('kare-kare', 3, 'Add kalabasa; simmer until easily pierced.'),
('kare-kare', 4, 'Serve with bagoong on the side.');

-- pinakbet
INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ('pinakbet', 'Pinakbet', 10, 'vegetable', 'shrimp_paste', 'TIER_1_FRESH', 'PRIORITY_3_FINISH_LAST', 295, 'Fill solids first, sauce after.', '000000000000000-00000-seed', 0);
INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES
('pinakbet', 0, 'kalabasa', 'Kalabasa', 'LARGE_DICE', NULL, 'granular', NULL, 50, 'g', NULL, NULL, NULL),
('pinakbet', 1, 'okra', 'Okra', 'HALVED', NULL, 'granular', NULL, 30, 'g', NULL, NULL, NULL),
('pinakbet', 2, 'eggplant', 'Eggplant', 'SLICED_ROUNDS', NULL, 'granular', NULL, 40, 'g', NULL, NULL, NULL),
('pinakbet', 3, 'ampalaya', 'Ampalaya', 'SLICED_ROUNDS', NULL, 'granular', NULL, 30, 'g', NULL, NULL, NULL),
('pinakbet', 4, 'sitaw', 'Sitaw', 'ROUGH_CHOP', NULL, 'granular', NULL, 30, 'g', NULL, NULL, NULL),
('pinakbet', 5, 'tomato', 'Tomato', 'MEDIUM_DICE', NULL, 'granular', NULL, 20, 'g', NULL, NULL, NULL),
('pinakbet', 6, 'bagoong', 'Shrimp paste (bagoong)', 'NONE', NULL, 'continuous', NULL, 10, 'g', '250 g jar', 250, 1),
('pinakbet', 7, 'garlic', 'Garlic', 'MINCED', NULL, 'granular', NULL, 2, 'g', NULL, NULL, NULL),
('pinakbet', 8, 'cooking_oil', 'Cooking oil', 'NONE', NULL, 'continuous', NULL, 3, 'ml', '1 L bottle', 1000, 1);
INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES
('pinakbet', 0, 'Sauté garlic and tomato until jammy.'),
('pinakbet', 1, 'Stir in bagoong until fragrant.'),
('pinakbet', 2, 'Layer kalabasa first, then the other vegetables; cover and steam until tender-crisp.'),
('pinakbet', 3, 'Toss gently once and finish until the vegetables glisten.');

-- pork-adobo
INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ('pork-adobo', 'Pork Adobo', 10, 'pork', 'soy_vinegar', 'TIER_2_HARDY', 'PRIORITY_1_SLOW_BRAISE', 460, 'Fill solids first, sauce after.', '000000000000000-00000-seed', 0);
INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES
('pork-adobo', 0, 'pork_belly', 'Pork belly', 'LARGE_DICE', 'Ask for 1-inch adobo cuts', 'discrete', 3, 100, 'g', NULL, NULL, NULL),
('pork-adobo', 1, 'garlic', 'Garlic', 'MINCED', NULL, 'granular', NULL, 6, 'g', NULL, NULL, NULL),
('pork-adobo', 2, 'soy_sauce', 'Soy sauce', 'NONE', NULL, 'continuous', NULL, 30, 'ml', '385 mL bottle', 385, 1),
('pork-adobo', 3, 'vinegar', 'Vinegar', 'NONE', NULL, 'continuous', NULL, 25, 'ml', '385 mL bottle', 385, 1),
('pork-adobo', 4, 'bay_leaf', 'Bay leaf', 'WHOLE', NULL, 'discrete', 1, 0.2, 'pc', 'pack of 20 leaves', 20, 1);
INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES
('pork-adobo', 0, 'Combine pork, soy sauce, vinegar, garlic and bay leaf; rest until well coated.'),
('pork-adobo', 1, 'Bring to a simmer without stirring until the vinegar smell mellows.'),
('pork-adobo', 2, 'Braise covered on low until the pork is fork-tender.'),
('pork-adobo', 3, 'Uncover and reduce until the sauce clings and glistens.');

-- pork-giniling
INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ('pork-giniling', 'Pork Giniling', 10, 'pork', 'tomato', 'TIER_2_HARDY', 'PRIORITY_2_FAST_SAUTE', 505, 'Fill solids first, sauce after.', '000000000000000-00000-seed', 0);
INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES
('pork-giniling', 0, 'ground_pork', 'Ground pork', 'NONE', NULL, 'continuous', NULL, 100, 'g', NULL, NULL, NULL),
('pork-giniling', 1, 'potato', 'Potato', 'SMALL_DICE', 'Cubitos', 'granular', NULL, 45, 'g', NULL, NULL, NULL),
('pork-giniling', 2, 'carrot', 'Carrot', 'SMALL_DICE', NULL, 'granular', NULL, 25, 'g', NULL, NULL, NULL),
('pork-giniling', 3, 'red_onion', 'Red onion', 'SMALL_DICE', NULL, 'granular', NULL, 25, 'g', NULL, NULL, NULL),
('pork-giniling', 4, 'garlic', 'Garlic', 'MINCED', NULL, 'granular', NULL, 3, 'g', NULL, NULL, NULL),
('pork-giniling', 5, 'tomato_sauce', 'Tomato sauce', 'NONE', NULL, 'continuous', NULL, 20, 'g', '250 g pouch', 250, 1),
('pork-giniling', 6, 'cooking_oil', 'Cooking oil', 'NONE', NULL, 'continuous', NULL, 3, 'ml', '1 L bottle', 1000, 1);
INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES
('pork-giniling', 0, 'Sauté onion and garlic in hot oil until glassy and fragrant.'),
('pork-giniling', 1, 'Crumble in ground pork; stir until no pink remains.'),
('pork-giniling', 2, 'Pour in tomato sauce and a splash of water; simmer until thickened.'),
('pork-giniling', 3, 'Fold in potatoes and carrots; cover and simmer until easily pierced.');

-- pork-kaldereta
INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ('pork-kaldereta', 'Pork Kaldereta', 10, 'pork', 'tomato', 'TIER_2_HARDY', 'PRIORITY_1_SLOW_BRAISE', 540, 'Fill solids first, sauce after.', '000000000000000-00000-seed', 0);
INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES
('pork-kaldereta', 0, 'pork_shoulder', 'Pork shoulder', 'LARGE_DICE', 'Ask for 1-inch adobo cuts', 'discrete', 3, 90, 'g', NULL, NULL, NULL),
('pork-kaldereta', 1, 'potato', 'Potato', 'LARGE_DICE', NULL, 'discrete', 2, 45, 'g', NULL, NULL, NULL),
('pork-kaldereta', 2, 'carrot', 'Carrot', 'ROLL_CUT', NULL, 'granular', NULL, 30, 'g', NULL, NULL, NULL),
('pork-kaldereta', 3, 'red_onion', 'Red onion', 'MEDIUM_DICE', NULL, 'granular', NULL, 15, 'g', NULL, NULL, NULL),
('pork-kaldereta', 4, 'bell_pepper', 'Bell pepper', 'LARGE_DICE', NULL, 'granular', NULL, 20, 'g', NULL, NULL, NULL),
('pork-kaldereta', 5, 'garlic', 'Garlic', 'MINCED', NULL, 'granular', NULL, 3, 'g', NULL, NULL, NULL),
('pork-kaldereta', 6, 'tomato_sauce', 'Tomato sauce', 'NONE', NULL, 'continuous', NULL, 18, 'g', '250 g pouch', 250, 1),
('pork-kaldereta', 7, 'liver_spread', 'Liver spread', 'NONE', NULL, 'continuous', NULL, 8.5, 'g', '85 g can', 85, 1),
('pork-kaldereta', 8, 'cooking_oil', 'Cooking oil', 'NONE', NULL, 'continuous', NULL, 3, 'ml', '1 L bottle', 1000, 1);
INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES
('pork-kaldereta', 0, 'Sear pork in smoking oil until browned on all edges; transfer to plate.'),
('pork-kaldereta', 1, 'Sauté prepped onions on medium until glassy, followed by garlic until golden.'),
('pork-kaldereta', 2, 'Add tomato sauce, liver spread, browned pork, and water.'),
('pork-kaldereta', 3, 'Drop heat to low, cover, and braise until fork-tender.'),
('pork-kaldereta', 4, 'Add prepped potatoes, carrots and peppers; simmer covered until easily pierced.');

-- pork-menudo
INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ('pork-menudo', 'Pork Menudo', 10, 'pork', 'tomato', 'TIER_2_HARDY', 'PRIORITY_1_SLOW_BRAISE', 470, 'Fill solids first, sauce after.', '000000000000000-00000-seed', 0);
INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES
('pork-menudo', 0, 'pork_shoulder', 'Pork shoulder', 'MEDIUM_DICE', 'Ask for menudo strips', 'discrete', 4, 80, 'g', NULL, NULL, NULL),
('pork-menudo', 1, 'potato', 'Potato', 'MEDIUM_DICE', NULL, 'discrete', 2, 35, 'g', NULL, NULL, NULL),
('pork-menudo', 2, 'carrot', 'Carrot', 'MEDIUM_DICE', NULL, 'granular', NULL, 25, 'g', NULL, NULL, NULL),
('pork-menudo', 3, 'red_onion', 'Red onion', 'MEDIUM_DICE', NULL, 'granular', NULL, 15, 'g', NULL, NULL, NULL),
('pork-menudo', 4, 'garlic', 'Garlic', 'MINCED', NULL, 'granular', NULL, 3, 'g', NULL, NULL, NULL),
('pork-menudo', 5, 'tomato_sauce', 'Tomato sauce', 'NONE', NULL, 'continuous', NULL, 20, 'g', '250 g pouch', 250, 1),
('pork-menudo', 6, 'soy_sauce', 'Soy sauce', 'NONE', NULL, 'continuous', NULL, 8, 'ml', '385 mL bottle', 385, 1),
('pork-menudo', 7, 'cooking_oil', 'Cooking oil', 'NONE', NULL, 'continuous', NULL, 3, 'ml', '1 L bottle', 1000, 1);
INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES
('pork-menudo', 0, 'Sear pork in smoking oil until browned; set aside.'),
('pork-menudo', 1, 'Sauté onions until glassy, then garlic until golden.'),
('pork-menudo', 2, 'Return pork with tomato sauce, soy sauce and water.'),
('pork-menudo', 3, 'Cover and braise on low until the pork is fork-tender.'),
('pork-menudo', 4, 'Add potatoes and carrots; simmer until easily pierced.');

-- pork-nilaga
INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ('pork-nilaga', 'Pork Nilaga', 10, 'pork', 'clear_broth', 'TIER_2_HARDY', 'PRIORITY_1_SLOW_BRAISE', 435, 'Fill solids first, sauce after.', '000000000000000-00000-seed', 0);
INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES
('pork-nilaga', 0, 'pork_hock', 'Pork hock', 'LARGE_DICE', 'Ask for hock cut into chunks', 'discrete', 3, 100, 'g', NULL, NULL, NULL),
('pork-nilaga', 1, 'potato', 'Potato', 'QUARTERED', NULL, 'discrete', 2, 45, 'g', NULL, NULL, NULL),
('pork-nilaga', 2, 'cabbage', 'Cabbage', 'ROUGH_CHOP', NULL, 'granular', NULL, 0.1, 'head', NULL, NULL, NULL),
('pork-nilaga', 3, 'red_onion', 'Red onion', 'QUARTERED', NULL, 'granular', NULL, 20, 'g', NULL, NULL, NULL),
('pork-nilaga', 4, 'fish_sauce', 'Fish sauce', 'NONE', NULL, 'continuous', NULL, 8, 'ml', '350 mL bottle', 350, 1);
INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES
('pork-nilaga', 0, 'Boil pork with onion until scum rises; skim and discard.'),
('pork-nilaga', 1, 'Cover and simmer on low until the pork is fork-tender.'),
('pork-nilaga', 2, 'Add potatoes; simmer until easily pierced.'),
('pork-nilaga', 3, 'Season with fish sauce, then lay in cabbage until just wilted.');

-- sinigang-baboy
INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ('sinigang-baboy', 'Sinigang na Baboy', 10, 'pork', 'clear_broth', 'TIER_1_FRESH', 'PRIORITY_1_SLOW_BRAISE', 505, 'Fill solids first, sauce after.', '000000000000000-00000-seed', 0);
INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES
('sinigang-baboy', 0, 'pork_belly', 'Pork belly', 'LARGE_DICE', 'Ask for 1-inch cuts with some bone', 'discrete', 3, 100, 'g', NULL, NULL, NULL),
('sinigang-baboy', 1, 'radish', 'Radish', 'SLICED_ROUNDS', NULL, 'granular', NULL, 30, 'g', NULL, NULL, NULL),
('sinigang-baboy', 2, 'kangkong', 'Kangkong', 'ROUGH_CHOP', NULL, 'granular', NULL, 0.1, 'pack', NULL, NULL, NULL),
('sinigang-baboy', 3, 'tomato', 'Tomato', 'QUARTERED', NULL, 'granular', NULL, 20, 'g', NULL, NULL, NULL),
('sinigang-baboy', 4, 'red_onion', 'Red onion', 'QUARTERED', NULL, 'granular', NULL, 15, 'g', NULL, NULL, NULL),
('sinigang-baboy', 5, 'sinigang_mix', 'Sinigang mix', 'NONE', NULL, 'continuous', NULL, 4, 'g', '40 g sachet', 40, 1),
('sinigang-baboy', 6, 'fish_sauce', 'Fish sauce', 'NONE', NULL, 'continuous', NULL, 8, 'ml', '350 mL bottle', 350, 1);
INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES
('sinigang-baboy', 0, 'Boil pork with onion and tomato; skim until the broth runs clear.'),
('sinigang-baboy', 1, 'Cover and simmer on low until the pork is fork-tender.'),
('sinigang-baboy', 2, 'Stir in sinigang mix until the broth turns pleasantly sour.'),
('sinigang-baboy', 3, 'Add radish; simmer until easily pierced.'),
('sinigang-baboy', 4, 'Drop in kangkong and turn off the heat once wilted.');
