import type { GlobalPriceRegistry, Recipe } from "../src/domain/schemas/blueprint";
import type { IngredientMeta } from "../src/domain/schemas/app";
import { SEED_HLC } from "../src/domain/sync/protocol";

type SeedInput = { recipes: readonly Recipe[]; registry: GlobalPriceRegistry; meta: Readonly<Record<string, IngredientMeta>> };

const q = (v: string | number | boolean | null | undefined): string =>
  v === null || v === undefined ? "NULL" : typeof v === "number" ? String(v) : typeof v === "boolean" ? (v ? "1" : "0") : `'${v.replace(/'/g, "''")}'`;
const row = (...vs: (string | number | boolean | null | undefined)[]) => `(${vs.map(q).join(", ")})`;
const byKey = <T>(xs: readonly T[], key: (t: T) => string) => [...xs].sort((a, b) => (key(a) < key(b) ? -1 : key(a) > key(b) ? 1 : 0));

/**
 * Bootstrap data as SQL (migrations/0002_seed.sql), so the server starts with the same fixtures every
 * client bootstraps locally. Seed rows carry SEED_HLC and are never in change_log. GENERATED: do not edit;
 * tests/seed-sql.test.ts guards it.
 */
export function buildSeedSql(data: SeedInput): string {
  const out: string[] = [
    "-- GENERATED by worker/seedSql.ts from fixtures/. Do not edit by hand (run `npx vitest run tests/seed-sql.test.ts -u`).",
    "-- Same data every client bootstraps locally; stamped with SEED_HLC so any real edit wins; never in change_log.",
    "",
  ];
  const reg = byKey(Object.values(data.registry), (r) => r.ingredient_id);
  out.push(
    "INSERT INTO price_registry (ingredient_id, display_name, price_per_unit, pricing_unit, last_updated, hlc) VALUES",
    reg.map((r) => row(r.ingredient_id, r.display_name, r.price_per_unit, r.pricing_unit, r.last_updated, SEED_HLC)).join(",\n") + ";",
    "",
    "INSERT INTO price_observations (id, ingredient_id, kind, price, observed_at, cycle_id, device_id) VALUES",
    reg.map((r) => row(`seed:${r.ingredient_id}`, r.ingredient_id, "seed", r.price_per_unit, r.last_updated, null, "seed")).join(",\n") + ";",
    "",
    "INSERT INTO ingredient_meta (ingredient_id, aisle, storage_class, surface_prep, avg_unit_mass_g, updated_at) VALUES",
    byKey(Object.values(data.meta), (m) => m.ingredient_id)
      .map((m) => row(m.ingredient_id, m.aisle, m.storage_class, m.surface_prep, m.avg_unit_mass_g, SEED_HLC))
      .join(",\n") + ";",
    "",
  );
  for (const r of byKey(data.recipes, (x) => x.id)) {
    out.push(
      `-- ${r.id}`,
      `INSERT INTO recipes (id, name, default_portions, protein_category, sauce_base, perishability_tier, stove_priority, estimated_base_cost_php, pack_step, updated_at, deleted) VALUES ${row(r.id, r.name, r.default_portions, r.protein_category, r.sauce_base, r.perishability_tier, r.stove_priority, r.estimated_base_cost_php, r.pack_step, SEED_HLC, 0)};`,
    );
    if (r.videos.length > 0) {
      out.push(`INSERT INTO recipe_videos (recipe_id, ord, title, platform, url) VALUES\n${r.videos.map((v, i) => row(r.id, i, v.title, v.platform, v.url)).join(",\n")};`);
    }
    out.push(
      `INSERT INTO recipe_prep_items (recipe_id, ord, ingredient_id, display_name, cut_technique, cut_note, granularity, pieces_per_portion, quantity_per_portion, unit, pkg_retail_unit, pkg_pack_size, pkg_snap_to_whole_pack) VALUES\n${r.prep_items
        .map((p, i) => row(r.id, i, p.ingredient_id, p.display_name, p.cut_technique, p.cut_note, p.granularity, p.pieces_per_portion, p.quantity_per_portion, p.unit, p.packaging?.retail_unit, p.packaging?.pack_size, p.packaging ? p.packaging.snap_to_whole_pack : null))
        .join(",\n")};`,
      `INSERT INTO recipe_cook_steps (recipe_id, ord, text) VALUES\n${r.cook_steps.map((t, i) => row(r.id, i, t)).join(",\n")};`,
      "",
    );
  }
  return out.join("\n");
}
